# ใช้ตอน dev/test เท่านั้น: docker compose -f docker-compose.yaml -f docker-compose.override.yaml up -d
services:
  snmpsim:
    image: tandrup/snmpsim
    container_name: ims-snmpsim
    networks:
      - ims-internal
    volumes:
      - ./monitoring/snmpsim:/usr/share/snmpsim/data
    ports:
      - "1161:161/udp"

  node-red:
    environment:
      - NODE_ENV=development
