-- ============================================================================
-- Synthetic eap_backup schema for development, CI and demos.
--
-- The production eap_backup database is a restore of plant data and is not in
-- git. This file creates the subset of it that the drilling and VCP dashboards,
-- the VCP alert rules and migrations 084-086 read, so that the whole path can
-- run on generated data (scripts/mock/eap-mock-data.js) with no factory data.
--
-- Column names and the table/view split follow the objects the dashboards
-- query. Column types are reconstructed from how the dashboards and
-- migrations use each column; they are not a dump of the plant server.
--
-- Safety: this file refuses to run on a database that already holds these
-- tables without the public.mock_dataset marker, so it cannot be pointed at a
-- restored plant database by mistake. It is idempotent on a mock database.
--
-- Usage (inside the TimescaleDB container or any psql client):
--   psql -v ON_ERROR_STOP=1 -d eap_backup -f database/mock/eap_backup-schema.sql
-- ============================================================================

DO $$
BEGIN
    IF to_regclass('public.mock_dataset') IS NULL
       AND (to_regclass('public.machine_event') IS NOT NULL
            OR to_regclass('public.vcp_upp') IS NOT NULL) THEN
        RAISE EXCEPTION 'refusing to run: % already holds machine_event/vcp_upp and is not a mock database (no public.mock_dataset)', current_database();
    END IF;
END
$$;

CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Marker: every row the generator writes is traceable to one run.
CREATE TABLE IF NOT EXISTS public.mock_dataset (
    run_id       text PRIMARY KEY,
    generated_at timestamptz NOT NULL DEFAULT now(),
    seed         bigint NOT NULL,
    hours        numeric NOT NULL,
    generator    text NOT NULL
);
COMMENT ON TABLE public.mock_dataset IS 'Marks this database as synthetic. One row per generator run. Created by database/mock/eap_backup-schema.sql.';

-- ---------------------------------------------------------------- drilling
CREATE TABLE IF NOT EXISTS public.machine_event (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    message_id     text,
    equipment_id   text,
    message_type   text,
    event_type     text,
    event_code     text,
    event_message  text,
    event_time     timestamptz NOT NULL,
    sent_time      timestamptz,
    received_at    timestamptz DEFAULT now(),
    source         text,
    source_file    text,
    magazine_no    text,
    spindle        text,
    raw_item_code  text
);
SELECT create_hypertable('public.machine_event', 'event_time', chunk_time_interval => INTERVAL '1 day', if_not_exists => true);
CREATE INDEX IF NOT EXISTS ix_mock_machine_event_eqp_time ON public.machine_event (equipment_id, event_time DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.machine_telemetry (
    message_id     text,
    equipment_id   text,
    event_time     timestamptz,
    sent_time      timestamptz,
    received_at    timestamptz DEFAULT now(),
    telemetry_data jsonb
);

CREATE TABLE IF NOT EXISTS public.eap_status (
    equipment_id   text PRIMARY KEY,
    message_id     text,
    agent_status   text,
    current_file   text,
    last_data_time timestamptz,
    last_error     text,
    heartbeat      timestamptz,
    event_time     timestamptz,
    sent_time      timestamptz,
    received_at    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.agent_log (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    message_id   text,
    equipment_id text,
    level        text,
    event_name   text,
    message      text,
    event_time   timestamptz NOT NULL,
    sent_time    timestamptz,
    received_at  timestamptz DEFAULT now()
);
SELECT create_hypertable('public.agent_log', 'event_time', chunk_time_interval => INTERVAL '7 days', if_not_exists => true);

-- Machine registry: the factory each drilling machine belongs to (Fleet
-- Overview label and factory filter). Same definition as migration 089.
CREATE TABLE IF NOT EXISTS public.machine_master (
    equipment_id VARCHAR(100) NOT NULL,
    brand        VARCHAR(50),
    model        VARCHAR(50),
    factory      VARCHAR(5),
    CONSTRAINT pk_machine_master PRIMARY KEY (equipment_id)
);

-- ---------------------------------------------------------------- vcp
-- One row per line per minute. 18 rectifier stations, two sides (a/b) each;
-- 18 pumps; nine baths. The source swaps the bath tags: preset_<bath> is the
-- reading and actual_<bath> the setpoint (see migration 086, vcp.upp).
DO $$
DECLARE
    cols text := '';
    bath text;
    i int;
BEGIN
    IF to_regclass('public.vcp_upp') IS NOT NULL THEN
        RETURN;
    END IF;
    FOREACH bath IN ARRAY ARRAY['clean','copperplating1','copperplating2','ao','hotwater','dry','heating','peeloff','rectifier'] LOOP
        cols := cols || format(', actual_%s numeric, preset_%s numeric', bath, bath);
    END LOOP;
    FOR i IN 1..18 LOOP
        cols := cols || format(', actual_current_%sa numeric, actual_current_%sb numeric', i, i)
                     || format(', preset_current_%sa numeric, preset_current_%sb numeric', i, i)
                     || format(', actual_voltage_%sa numeric, actual_voltage_%sb numeric', i, i)
                     || format(', actual_pump_%s numeric, preset_pump_%s numeric', i, i)
                     || format(', preset_amp_%sa numeric', i);
        -- the source table has no preset_amp_15b column; keep the shape
        IF i <> 15 THEN
            cols := cols || format(', preset_amp_%sb numeric', i);
        END IF;
    END LOOP;
    EXECUTE 'CREATE TABLE public.vcp_upp (
        log_id text NOT NULL,
        log_date timestamptz NOT NULL,
        trx_id text,
        jobkey text,
        equipment_id text,
        factory text,
        "timestamp" text,
        waveform text,
        line_speed numeric,
        plating_time numeric,
        density numeric,
        thickness numeric,
        width numeric,
        height numeric,
        plating_area_a numeric,
        plating_area_b numeric,
        copper_a_preset_current numeric,
        copper_b_preset_current numeric,
        current_check text,
        frequency_check text,
        pump_frequency numeric,
        actual_frequency_1 numeric,
        preset_frequency_1 numeric,
        shielding_board numeric,
        actual_shielding_board numeric,
        preset_shielding_board numeric,
        copper_thick_low numeric,
        copper_thick_high numeric,
        actual_tank numeric,
        preset_tank numeric,
        actual_amp_1a numeric,
        actual_amp_1b numeric,
        actual_prep numeric,
        pre_clean numeric,
        preset_cleaning_temp numeric,
        actual_cleaning_temp numeric' || cols || ')';
END
$$;
SELECT create_hypertable('public.vcp_upp', 'log_date', chunk_time_interval => INTERVAL '7 days', if_not_exists => true);
CREATE INDEX IF NOT EXISTS ix_mock_vcp_upp_eqp_time ON public.vcp_upp (equipment_id, log_date DESC);

CREATE TABLE IF NOT EXISTS public.vcp_alarm (
    log_id       text NOT NULL,
    log_date     timestamptz NOT NULL,
    equipment_id text,
    job_key      text,
    error_code   text,
    error_msg    text,
    error_type   text,
    alarm_status text,
    error_time   text,
    factory      text,
    process      text
);
SELECT create_hypertable('public.vcp_alarm', 'log_date', chunk_time_interval => INTERVAL '7 days', if_not_exists => true);
CREATE INDEX IF NOT EXISTS ix_mock_vcp_alarm_eqp_time ON public.vcp_alarm (equipment_id, log_date DESC);

CREATE TABLE IF NOT EXISTS public.vcp_status_change (
    log_id          text NOT NULL,
    log_date        timestamptz NOT NULL,
    transaction_id  text,
    equipment_id    text,
    event_time      text,
    current_status  text,
    previous_status text,
    factory         text
);
SELECT create_hypertable('public.vcp_status_change', 'log_date', chunk_time_interval => INTERVAL '7 days', if_not_exists => true);
CREATE INDEX IF NOT EXISTS ix_mock_vcp_status_eqp_time ON public.vcp_status_change (equipment_id, log_date DESC);

-- The dashboards and alert rules read the old API names; on the plant server
-- these are passthrough views over the vcp_* tables, and so they are here.
CREATE OR REPLACE VIEW public.eap_api_vcp_upp AS SELECT * FROM public.vcp_upp;
CREATE OR REPLACE VIEW public.eap_api_vcp_alarm AS SELECT * FROM public.vcp_alarm;
CREATE OR REPLACE VIEW public.eap_api_vcp_status_change AS SELECT * FROM public.vcp_status_change;

-- ------------------------------------------------ ldi and shopfloor (empty)
-- Migrations 084 and 086 comment on and wrap these; the generator leaves them
-- empty. Quoted and CamelCase names match the physical names 086 reads.
CREATE TABLE IF NOT EXISTS public."DFI_LDI_ALARM_LOG" (
    "LogId" text, "LogDate" timestamp, "ErrorCode" text, "ErrorTime" timestamp,
    "EquipmentID" text, "Factory" text, "Process" text
);
CREATE TABLE IF NOT EXISTS public."DFI_LDI_ALARM_MS_CODE" (
    "AlarmId" text, "AlarmType" text, "AlarmCode" text, "AlarmMsg" text, "AlarmDetail" text
);
CREATE TABLE IF NOT EXISTS public."MachineAlarm" (
    "AlarmId" text, "AlarmType" text, "AlarmCode" text, "AlarmMsg" text, "AlarmDetail" text
);
CREATE TABLE IF NOT EXISTS public.machine_process_log (
    "LogId" text, "LogDate" timestamp, "MO" text, "FPN" text, "UserID" text,
    "ResistDosage" varchar, "LayerName" varchar, "ScaleX" varchar, "ScaleY" varchar,
    "ScaleMode" varchar, "PE" varchar, "JE" varchar, "Temperature" varchar, "Humidity" varchar,
    "EquipmentID" text, "JESetting" varchar, "PESetting" varchar, "State" varchar,
    "Resist" varchar, "ScanSpeed" varchar, "AirVacuum" varchar, "Thickness" varchar,
    "PrintedNumber" varchar, "TotalNumber" varchar, "StartTime" timestamp,
    "EndTime" timestamp, "Factory" text, "Process" text, "EqpTrxId" text,
    "FilmNo" text, "BoardID" text, "ProcessStartTime" timestamp, "ProcessEndTime" timestamp
);
CREATE TABLE IF NOT EXISTS public.machine_alarm_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    eqp_id text, event_time timestamp, report_type text, alarm_type text,
    alarm_code text, created_at timestamp DEFAULT now()
);

-- Dashboard role: exists on the real stack (created by the ims migrations);
-- create it here only when a standalone mock server lacks it.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'grafana_reader') THEN
        CREATE ROLE grafana_reader NOLOGIN;
    END IF;
END
$$;
GRANT USAGE ON SCHEMA public TO grafana_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana_reader;

INSERT INTO public.mock_dataset (run_id, seed, hours, generator)
VALUES ('schema', 0, 0, 'database/mock/eap_backup-schema.sql')
ON CONFLICT (run_id) DO NOTHING;
