/**
 * Floor registry tests — services/factory-twin-3d/lib/floors.js
 *
 * The registry turns a client-supplied string into a filesystem path, so most
 * of what follows is a traversal and confusion suite rather than a shape suite.
 * The property being asserted throughout is that a path is only ever built from
 * an id the SERVER produced by reading its own directory — never from the
 * string a request carried, however well-formed that string looked.
 *
 * Fixtures write into a temporary directory. Nothing here reads or creates a
 * real private document.
 *
 * Run: node tests/unit/factory-twin-floors.test.js
 */

'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const floors = require('../../services/factory-twin-3d/lib/floors');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  PASS  ${name}`);
    passed++;
  } catch (err) {
    console.log(`  FAIL  ${name}`);
    console.log(`        ${err.message}`);
    failed++;
  }
}

/** A private directory holding the named floors, and nothing real. */
function fixtureDir(ids, extra = []) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'twin-floors-'));
  for (const id of ids) {
    fs.writeFileSync(path.join(dir, `${id}-geometry.json`), '{"equipment":[]}\n');
  }
  for (const name of extra) fs.writeFileSync(path.join(dir, name), '{}\n');
  return dir;
}

// ── the id space ────────────────────────────────────────────

test('a floor id is exactly floor1 through floor5 and nothing else', () => {
  for (const good of ['floor1', 'floor2', 'floor3', 'floor4', 'floor5']) {
    assert.strictEqual(floors.isFloorId(good), true, good);
  }
  const bad = [
    'floor0', 'floor6', 'floor10', 'FLOOR1', 'Floor1', 'floor', '1',
    'floor1 ', ' floor1', 'floor1.json', 'floor1/x', 'floor1\\x',
    '../floor1', 'floor1%2e%2e', '', null, undefined, 0, 1, {}, [], ['floor1'],
  ];
  for (const value of bad) {
    assert.strictEqual(floors.isFloorId(value), false, JSON.stringify(value));
  }
});

test('a trailing newline cannot smuggle a valid id past the pattern', () => {
  // A pattern anchored with ^ and $ alone would accept this, because in
  // JavaScript $ also matches immediately before a final newline. A path built
  // from it would still name floor1-geometry.json on most filesystems, so the
  // acceptance would not even be visibly wrong.
  assert.strictEqual(floors.isFloorId('floor1\n'), false);
  assert.strictEqual(floors.isFloorId('\nfloor1'), false);
});

test('the ordinal comes from the id, and only from an id', () => {
  assert.strictEqual(floors.ordinalOf('floor3'), 3);
  assert.strictEqual(floors.ordinalOf('floor9'), null);
  assert.strictEqual(floors.ordinalOf('../../etc/passwd'), null);
});

// ── discovery ───────────────────────────────────────────────

test('only floors with a geometry document are deployed', () => {
  const dir = fixtureDir(['floor1', 'floor3'], ['floor2-zones.json']);
  const list = floors.discover(dir);
  assert.deepStrictEqual(list.map((f) => f.id), ['floor1', 'floor3']);
});

test('a floor with zones but no geometry is not a floor', () => {
  // Zones without an envelope have nothing to be placed on, and reporting the
  // floor as deployed would promise geometry that is not there.
  const dir = fixtureDir([], ['floor2-zones.json', 'floor2-asset-mapping.json']);
  assert.deepStrictEqual(floors.discover(dir), []);
});

test('discovery reports optional layers without inventing them', () => {
  const dir = fixtureDir(['floor1'], ['floor1-zones.json']);
  const [f] = floors.discover(dir);
  assert.strictEqual(f.has_zones, true);
  assert.strictEqual(f.has_mapping, false);
});

test('a label is computed from the ordinal, never read from a document', () => {
  const dir = fixtureDir(['floor4']);
  const [f] = floors.discover(dir);
  assert.strictEqual(f.label, 'Floor 4');
  assert.deepStrictEqual(Object.keys(f).sort(),
    ['has_mapping', 'has_zones', 'id', 'label', 'ordinal']);
});

test('a file that merely looks like a floor document is not discovered', () => {
  const dir = fixtureDir([], [
    'floor6-geometry.json', 'floor-geometry.json',
    'floor1_geometry.json', 'floor1-geometry.json.bak',
  ]);
  assert.deepStrictEqual(floors.discover(dir), []);
});

test('a differently-cased filename still yields the canonical lowercase id', () => {
  // Windows and macOS fold case, so FLOOR1-geometry.json satisfies an
  // existsSync for the lowercase name and the floor is found. That is a
  // filesystem property, not a registry one, and it is harmless -- what would
  // NOT be harmless is the catalogue then carrying the mixed-case string
  // onward, since every later path is built from the catalogue's id. The id
  // is generated by the registry, never read off the directory entry, so it
  // is lowercase on every platform.
  const dir = fixtureDir([], ['FLOOR1-geometry.json']);
  for (const f of floors.discover(dir)) {
    assert.strictEqual(f.id, 'floor1');
    assert.strictEqual(floors.isFloorId(f.id), true);
  }
});

test('discovery of a directory that does not exist is empty, not a throw', () => {
  assert.deepStrictEqual(
    floors.discover(path.join(os.tmpdir(), 'twin-floors-absent-directory')), []);
});

// ── resolution ──────────────────────────────────────────────

test('resolve returns the catalogue own id, not the caller string', () => {
  const list = floors.discover(fixtureDir(['floor1']));
  // Assembled at runtime so it cannot be the same object as the catalogue's.
  const requested = ['f', 'l', 'o', 'o', 'r', '1'].join('');
  const out = floors.resolve(list, requested);
  assert.strictEqual(out, 'floor1');
  assert.strictEqual(out, list[0].id, 'the returned string must be the catalogue entry');
});

test('a well-formed id for an undeployed floor resolves to null, not the default', () => {
  const list = floors.discover(fixtureDir(['floor1']));
  assert.strictEqual(floors.resolve(list, 'floor2'), null);
  assert.strictEqual(floors.resolve(list, 'floor5'), null);
});

test('every traversal shape resolves to null', () => {
  const list = floors.discover(fixtureDir(['floor1']));
  const hostile = [
    '../floor1', 'floor1/../floor1', './floor1', 'floor1/', '/floor1',
    'C:\\floor1', 'floor1%00', 'floor1\u0000', '..%2f..%2ffloor1',
    'floor1?x', 'floor1#x', 'floor1;floor1',
  ];
  for (const value of hostile) {
    assert.strictEqual(floors.resolve(list, value), null, value);
  }
});

test('a prototype key cannot resolve to a floor', () => {
  const list = floors.discover(fixtureDir(['floor1']));
  for (const key of ['__proto__', 'constructor', 'prototype', 'toString']) {
    assert.strictEqual(floors.resolve(list, key), null, key);
  }
});

test('a non-string resolves to null rather than being coerced', () => {
  const list = floors.discover(fixtureDir(['floor1']));
  for (const value of [null, undefined, 1, ['floor1'], { id: 'floor1' }, true]) {
    assert.strictEqual(floors.resolve(list, value), null, JSON.stringify(value));
  }
});

test('resolving against an empty catalogue is null, never a guess', () => {
  assert.strictEqual(floors.resolve([], 'floor1'), null);
  assert.strictEqual(floors.resolve(null, 'floor1'), null);
});

test('the default floor is the lowest deployed one, in any discovery order', () => {
  const list = floors.discover(fixtureDir(['floor2', 'floor4']));
  assert.strictEqual(floors.defaultFloor(list), 'floor2');
  assert.strictEqual(floors.defaultFloor(list.slice().reverse()), 'floor2');
  assert.strictEqual(floors.defaultFloor([]), null);
});

// ── paths ───────────────────────────────────────────────────

test('a document path is built only from a valid id and a known kind', () => {
  const dir = path.join(os.tmpdir(), 'twin-floors-paths');
  assert.strictEqual(
    floors.documentPath(dir, 'floor1', 'geometry'),
    path.join(dir, 'floor1-geometry.json'));
  assert.strictEqual(floors.documentPath(dir, 'floor1', 'secrets'), null);
  assert.strictEqual(floors.documentPath(dir, '../floor1', 'geometry'), null);
});

test('a prototype key is not a document kind', () => {
  const dir = path.join(os.tmpdir(), 'twin-floors-paths');
  for (const kind of ['__proto__', 'constructor', 'toString', 'hasOwnProperty']) {
    assert.strictEqual(floors.documentPath(dir, 'floor1', kind), null, kind);
  }
});

test('no document path can escape the private directory', () => {
  const dir = path.resolve(os.tmpdir(), 'twin-floors-paths');
  for (const id of ['floor1', 'floor2', 'floor3', 'floor4', 'floor5']) {
    for (const kind of Object.keys(floors.DOCUMENTS)) {
      const p = floors.documentPath(dir, id, kind);
      assert.ok(p !== null, `${id}/${kind}`);
      assert.strictEqual(path.dirname(path.resolve(p)), dir, p);
    }
  }
});

test('the document kind map cannot be extended at runtime', () => {
  try {
    floors.DOCUMENTS.evil = '-evil.json';
  } catch (err) {
    // Strict mode throws; sloppy mode silently ignores. Either is acceptable,
    // the assertion below is the one that matters.
  }
  assert.ok(!('evil' in floors.DOCUMENTS));
  assert.strictEqual(floors.documentPath(os.tmpdir(), 'floor1', 'evil'), null);
});

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
